[package]
name = "arche"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
arche-foundation = { path = "../arche-foundation" }
arche-frontend = { path = "../arche-frontend" }
arche-package = { path = "../arche-package" }
arche-semantics = { path = "../arche-semantics" }
