[package]
name = "arche-semantics"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
arche-foundation = { path = "../arche-foundation" }
arche-frontend = { path = "../arche-frontend" }

[dev-dependencies]
arche-package = { path = "../arche-package" }
